### ISSUE TITLE
feat: 페이지 기본 설정

### ISSUE THREAD

**Issue by GEONU-MOON** [GEONU-MOON/dctrend#1]
## New Features

1. 페이지 기본 설정 구현

### Todos

- [x] 기존 main폴더의 main.html을 프로젝트 루트 페이지로 변경
- [x] Main.js 추가
- [x] Ent.js 추가
