### ISSUE TITLE
fix: 버그 수정

### ISSUE THREAD

**Issue by GEONU-MOON** [GEONU-MOON/dctrend#11]
## Fix

1. 버그 수정

### Todos

- [x] 상세 뉴스 페이지에서 카테고리 활성화
- [x] 상세 뉴스 페이지 실시간 랭킹 차트 삽입
- [x] 카테고리 뉴스 페이지에서 뉴스 영역 전체에 링크 걸기
- [x] 카테고리 뉴스 페이지에서 실시간 인기 기사와 최신 기사에 링크 걸기
