### ISSUE TITLE
fix : 버그 수정 및 html 형식 변환 보완

### ISSUE THREAD

**Issue by GEONU-MOON** [GEONU-MOON/dctrend#17]
## New Features

1. 버그 수정 및 html 형식 변환 보완

### Todos

- [x] 모든 html태그 다 빠지게 useCleanHtml.js 수정
- [x] 페이지 번호 클릭시 페이지 맨 위로 이동
- [x] 디테일 페이지 들어갔다가 이전 버튼 누르면 해당 위치에 남아있도록 수정
- [x] 모바일 버전 헤더에 슬라이드 메뉴 추가
- [x] 레이아웃 조정
- [x] 쿼리 파라미터에 페이지 번호 반영하여 페이지 번호 관리
