### ISSUE TITLE
feat: 카테고리 뉴스 페이지 보완

### ISSUE THREAD

**Issue by GEONU-MOON** [GEONU-MOON/dctrend#7]
## New Features

1. 카테고리 뉴스 페이지 수정 및 보완

### Todos

- [x] 활성화된 카테고리 탭에 css동적 적용
- [x] 최신 기사의 잘못된 이미지 url 수정
- [x] 인기기사/최신기사 렌더링 갯수 수정
